services:
  email-generator-service:
    image: email-generator-service
    container_name: email-generator-service
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./tls/keystore:/tls/keystore
    environment:
      - KEYSTORE_PATH=${KEYSTORE_PATH}
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
    networks:
      - service-network

  nginx:
    image: nginx:1.27
    ports:
      - "9443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/error_pages:/usr/share/nginx/html
    depends_on:
      - email-generator-service
    networks:
      - service-network

networks:
  service-network:
    driver: bridge
